version: 2
updates:
  - package-ecosystem: gradle
    directories:
      - "/arconia-docling"
      - "/arconia-dev-services/spring-data-jpa-mariadb"
      - "/arconia-dev-services/spring-data-jpa-mysql"
      - "/arconia-dev-services/spring-data-jpa-oracle"
      - "/arconia-dev-services/spring-data-jpa-oracle-xe"
      - "/arconia-dev-services/spring-data-jpa-postgresql"
      - "/arconia-dev-services/spring-data-redis"
      - "/arconia-dev-services/spring-rabbitmq"
      - "/arconia-multitenancy/tenant-source-properties"
      - "/arconia-multitenancy/web-http-server"
      - "/arconia-openinference"
      - "/arconia-opentelemetry/logging-log4j2"
      - "/arconia-opentelemetry/observability-signals"
    schedule:
      interval: daily
      time: "23:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps:"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps:"
