spring:
  application:
    name: logging-log4j2

management:
  endpoints:
    web:
      exposure:
        include: "*"

arconia:
  otel:
    metrics:
      exporter:
        interval: 5s
    resource:
      contributors:
        host:
          enabled: true
        java:
          enabled: true
        os:
          enabled: true
        process:
          enabled: true
