spring:
  application:
    name: tenant-source-properties

arconia:
  multitenancy:
    details:
      # Removed. Tenant details are auto-configured from the arconia.multitenancy.details.tenants list or from a tenant details dependency.
      # source: properties
      tenants:
        - identifier: dukes
        - identifier: beans
        - identifier: pixie
          enabled: false
          attributes:
            status: onboarding
