spring:
  application:
    name: tenant-source-properties

arconia:
  multitenancy:
    details:
      source: properties
      tenants:
        - identifier: dukes
        - identifier: beans
        - identifier: pixie
          enabled: false
          attributes:
            status: onboarding
