spring:
  application:
    name: observability-signals

management:
  endpoints:
    web:
      exposure:
        include: "*"

arconia:
  otel:
    metrics:
      interval: 5s
    resource:
      contributors:
        container:
          enabled: true
        host-id:
          enabled: true
        host:
          enabled: true
        java:
          enabled: true
        os:
          enabled: true
        process:
          enabled: true
