spring:
  application:
    name: arconia-openinference
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: ministral-3:8b
      embedding:
        options:
          model: granite-embedding:30m
