spring:
  application:
    name: docling-rag

  ai:
    ollama:
      init:
        pull-model-strategy: when-missing
      chat:
        model: ministral-3:8b
      embedding:
        model: granite-embedding:278m

    vectorstore:
      pgvector:
        dimensions: 768
        index-type: hnsw
        initialize-schema: true
